import Foundation

enum L10n {
    static var lang: Language = .en

    // Single source of truth for every translated string.
    // Keys are stable identifiers; values are per-language.
    static let table: [Language: [String: String]] = [
        .en: [
            // ── Footer ──
            "poll_now": "Poll Now",
            "open_dashboard": "Open Dashboard",
            "refresh_display": "Refresh Display",
            "add_new_agent": "Add New Agent",
            "manage_accounts": "Manage Accounts…",
            "language": "Language",
            "quit": "Quit",
            "heartbeat": "Heartbeat",
            "heartbeat_next": "Next",
            "heartbeat_last": "Last",
            "heartbeat_last_success": "Last success",
            "run_heartbeat_now": "Run Heartbeat Now",
            "heartbeat_success": "Success",
            "heartbeat_fail": "Fail",
            "heartbeat_unknown": "Unknown",
            "reconnect_agent": "Reconnect This Account",
            "swap_to_agent": "Swap to This Account",
            "devin_api_key_title": "Reconnect Devin",
            "devin_api_key_message": "Enter the API key for this Devin account.",
            "delete_agent": "Delete This Agent",
            "delete_agent_confirm": "Remove %@ from the agent pool? This cannot be undone.",
            "cancel": "Cancel",
            // ── Group headers ──
            "status": "Status",
            "limit_session": "Limit session",
            "resets": "Resets",
            "subscription": "Subscription",
            // ── Labels ──
            "plan": "Plan",
            "token_expires": "Token expires",
            "last_poll": "Last poll",
            "additional_credits": "Additional credits",
            "banked_resets": "Banked resets",
            "binding_window": "Binding window",
            "rate_limit_tier": "Rate limit tier",
            "billing": "Billing",
            "extra_usage": "Extra usage",
            "subscribed": "Subscribed",
            "member_since": "Member since",
            "org": "Org",
            "account": "Account",
            "monthly_credits": "Monthly credits",
            "on_demand_cap": "On-demand cap",
            "billing_period": "Billing period",
            "tier": "Tier",
            "description": "Description",
            "active_session_tier": "Active session tier",
            "premium_entitlement": "Premium entitlement",
            "premium_overage": "Premium overage",
            "chat": "Chat",
            "completions": "Completions",
            "upgradeable": "Upgradeable",
            "credit_balance": "Credit balance",
            "plan_started": "Plan started",
            "plan_resets": "Plan resets",
            "plan_expires": "Plan expires",
            "remaining": "Remaining",
            "reset": "Reset",
            "limit": "Limit",
            "monthly": "Monthly",
            "sku": "SKU",
            "quota_limit": "Quota limit",
            "quota_reset": "Quota reset",
            "account_created": "Account created",
            "payment_history": "Previous payments",
            // ── Messages ──
            "no_details": "No details",
            "na": "n/a",
            "updated": "UPDATED",
            "loading": "Loading…",
            // ── Booleans ──
            "on": "on",
            "off": "off",
            "unlimited": "unlimited",
            "limited": "limited",
            "yes": "yes",
            "no": "no",
            // ── Limit names ──
            "5h_limit": "5h limit",
            "weekly_limit": "weekly limit",
            "fable_limit": "Fable limit",
            "fable_rate_limited": "rate-limited",
            "monthly_limit": "monthly limit",
            "daily_tokens": "daily tokens",
            "tier_usage": "tier usage",
            "ag_group_gemini": "Gemini models",
            "ag_group_other": "Claude & GPT models",
            "premium_requests": "premium requests",
            "chat_limit": "chat",
            "daily_limit": "daily limit",
            // ── Window labels (detailLines) ──
            "window_label": "window",
            "window_monthly": "monthly",
            "window_quota": "quota",
            "window_tier": "tier",
            "window_win": "win",
            "window_24h_tokens": "24h tokens",
            // ── Misc ──
            "used": "used",
            "credits": "credits",
            "expire_label": "expire",
            "issued_label": "issued",
            "coupon_reason_label": "Reason",
            "coupon_issued_label": "Issued",
            "coupon_expire_label": "Expire",
            "reset_coupons": "Reset coupons",
            "coupon_usage": "usage",
            "coupon_referral": "referral",
            "warn_weekly_closing": "resets in %dh — weekly limit closing",
            "weekly_short": "weekly",
            "finishes_soon": "End Soon",
            // ── Layout experiment (usable-first, spec §2) ──
            "layout": "Layout",
            "layout_classic": "Classic",
            "layout_usable_first": "Usable-first",
            "use_now_header": "USE NOW",
            "limited_header": "LIMITED / COOLING DOWN",
            "blocked_header": "BLOCKED",
            "other_header": "OTHER",
            "usable_count": "usable",
            "pct_left": "left",
            "resets_in": "resets in %@",
            "usable_now": "reset · usable now",
            "quota_exhausted": "quota exhausted",
            "token_expired_reconnect": "token expired · reconnect",
            "error_prefix": "error",
            "sub_expired_on": "sub expired %@",
            // ── Subscription line (account submenus) ──
            "sub_paid": "paid",
            "sub_free": "free",
            "sub_renews": "renews %@",
            "sub_renews_soon": "renews soon %@",
            "sub_expired_since": "expired since %@",
            "sub_expired": "expired",
        ],
        .ko: [
            // ── Footer ──
            "poll_now": "지금 업데이트",
            "open_dashboard": "대시보드 열기",
            "refresh_display": "표시 새로고침",
            "add_new_agent": "새 에이전트 추가",
            "manage_accounts": "계정 관리…",
            "language": "언어",
            "quit": "종료",
            "heartbeat": "Heartbeat",
            "heartbeat_next": "다음",
            "heartbeat_last": "마지막",
            "heartbeat_last_success": "마지막 성공",
            "run_heartbeat_now": "지금 하트비트 실행",
            "heartbeat_success": "성공",
            "heartbeat_fail": "실패",
            "heartbeat_unknown": "알 수 없음",
            "reconnect_agent": "계정 다시 연결하기",
            "swap_to_agent": "이 계정으로 전환하기",
            "devin_api_key_title": "Devin 다시 연결",
            "devin_api_key_message": "이 Devin 계정의 API 키를 입력하세요.",
            "delete_agent": "이 에이전트 삭제",
            "delete_agent_confirm": "%@ 를 에이전트 풀에서 삭제하시겠습니까? 되돌릴 수 없습니다.",
            "cancel": "취소",
            // ── Group headers ──
            "status": "상태",
            "limit_session": "제한 세션",
            "resets": "리셋",
            "subscription": "구독",
            // ── Labels ──
            "plan": "플랜",
            "token_expires": "토큰 만료",
            "last_poll": "마지막 업데이트",
            "additional_credits": "추가 크레딧",
            "banked_resets": "적립 리셋",
            "binding_window": "바인딩 윈도우",
            "rate_limit_tier": "레이트 리밋 티어",
            "billing": "청구",
            "extra_usage": "추가 사용",
            "subscribed": "구독 시작",
            "member_since": "가입일",
            "org": "조직",
            "account": "계정",
            "monthly_credits": "월간 크레딧",
            "on_demand_cap": "온디맨드 상한",
            "billing_period": "청구 기간",
            "tier": "티어",
            "description": "설명",
            "active_session_tier": "활성 세션 티어",
            "premium_entitlement": "프리미엄 권한",
            "premium_overage": "프리미엄 초과",
            "chat": "채팅",
            "completions": "컴플리션",
            "upgradeable": "업그레이드 가능",
            "credit_balance": "크레딧 잔액",
            "plan_started": "플랜 시작",
            "plan_resets": "플랜 리셋",
            "plan_expires": "플랜 만료",
            "remaining": "남음",
            "reset": "리셋",
            "limit": "한도",
            "monthly": "월간",
            "sku": "SKU",
            "quota_limit": "할당량 한도",
            "quota_reset": "할당량 리셋",
            "account_created": "계정 생성",
            "payment_history": "이전 결제",
            // ── Messages ──
            "no_details": "상세 정보 없음",
            "na": "정보 없음",
            "updated": "업데이트",
            "loading": "불러오는 중…",
            // ── Booleans ──
            "on": "켜짐",
            "off": "꺼짐",
            "unlimited": "무제한",
            "limited": "제한",
            "yes": "예",
            "no": "아니오",
            // ── Limit names ──
            "5h_limit": "5시간 제한",
            "weekly_limit": "주간 제한",
            "fable_limit": "Fable 제한",
            "fable_rate_limited": "제한 도달",
            "monthly_limit": "월간 제한",
            "daily_tokens": "일일 토큰",
            "tier_usage": "티어 사용량",
            "ag_group_gemini": "Gemini 모델",
            "ag_group_other": "Claude & GPT 모델",
            "premium_requests": "프리미엄 요청",
            "chat_limit": "채팅",
            "daily_limit": "일일 제한",
            // ── Window labels (detailLines) ──
            "window_label": "윈도우",
            "window_monthly": "월간",
            "window_quota": "할당량",
            "window_tier": "티어",
            "window_win": "윈도우",
            "window_24h_tokens": "24시간 토큰",
            // ── Misc ──
            "used": "사용",
            "credits": "크레딧",
            "expire_label": "만료",
            "issued_label": "발급",
            "coupon_reason_label": "사유",
            "coupon_issued_label": "발급",
            "coupon_expire_label": "만료",
            "reset_coupons": "리셋 쿠폰",
            "coupon_usage": "사용 보상",
            "coupon_referral": "추천",
            "warn_weekly_closing": "%d시간 후 리셋 — 주간 제한 마감",
            "weekly_short": "주간",
            "finishes_soon": "곧 종료",
            // ── Layout experiment (usable-first, spec §2) ──
            "layout": "레이아웃",
            "layout_classic": "클래식",
            "layout_usable_first": "사용 가능 우선",
            "use_now_header": "지금 사용",
            "limited_header": "제한 / 쿨다운",
            "blocked_header": "차단됨",
            "other_header": "기타",
            "usable_count": "사용 가능",
            "pct_left": "남음",
            "resets_in": "%@ 후 리셋",
            "usable_now": "리셋됨 · 사용 가능",
            "quota_exhausted": "할당량 소진",
            "token_expired_reconnect": "토큰 만료 · 다시 연결",
            "error_prefix": "오류",
            "sub_expired_on": "구독 만료 %@",
            // ── Subscription line (account submenus) ──
            "sub_paid": "결제 중",
            "sub_free": "무료",
            "sub_renews": "%@ 갱신",
            "sub_renews_soon": "곧 갱신 (%@)",
            "sub_expired_since": "%@부터 만료",
            "sub_expired": "만료됨",
        ],
        .zh: [
            // ── Footer ──
            "poll_now": "立即轮询",
            "open_dashboard": "打开仪表盘",
            "refresh_display": "刷新显示",
            "add_new_agent": "添加新代理",
            "manage_accounts": "管理账户…",
            "language": "语言",
            "quit": "退出",
            "heartbeat": "Heartbeat",
            "heartbeat_next": "下次",
            "heartbeat_last": "上次",
            "heartbeat_last_success": "上次成功",
            "run_heartbeat_now": "立即运行 Heartbeat",
            "heartbeat_success": "成功",
            "heartbeat_fail": "失败",
            "heartbeat_unknown": "未知",
            "reconnect_agent": "重新连接此账户",
            "swap_to_agent": "切换到此账户",
            "devin_api_key_title": "重新连接 Devin",
            "devin_api_key_message": "输入此 Devin 账户的 API 密钥。",
            "delete_agent": "删除此代理",
            "delete_agent_confirm": "从代理池中移除 %@？此操作无法撤销。",
            "cancel": "取消",
            // ── Group headers ──
            "status": "状态",
            "limit_session": "限制会话",
            "resets": "重置",
            "subscription": "订阅",
            // ── Labels ──
            "plan": "计划",
            "token_expires": "令牌过期",
            "last_poll": "最后轮询",
            "additional_credits": "额外积分",
            "banked_resets": "累积重置",
            "binding_window": "绑定窗口",
            "rate_limit_tier": "速率限制层级",
            "billing": "计费",
            "extra_usage": "额外使用",
            "subscribed": "订阅于",
            "member_since": "注册于",
            "org": "组织",
            "account": "账户",
            "monthly_credits": "每月积分",
            "on_demand_cap": "按需上限",
            "billing_period": "计费周期",
            "tier": "层级",
            "description": "描述",
            "active_session_tier": "当前会话层级",
            "premium_entitlement": "高级配额",
            "premium_overage": "高级超额",
            "chat": "聊天",
            "completions": "补全",
            "upgradeable": "可升级",
            "credit_balance": "积分余额",
            "plan_started": "计划开始",
            "plan_resets": "计划重置",
            "plan_expires": "计划到期",
            "remaining": "剩余",
            "reset": "重置",
            "limit": "限额",
            "monthly": "每月",
            "sku": "SKU",
            "quota_limit": "配额限制",
            "quota_reset": "配额重置",
            "account_created": "账户创建",
            "payment_history": "历史付款",
            // ── Messages ──
            "no_details": "无详情",
            "na": "暂无",
            "updated": "已更新",
            "loading": "加载中…",
            // ── Booleans ──
            "on": "开",
            "off": "关",
            "unlimited": "无限",
            "limited": "有限",
            "yes": "是",
            "no": "否",
            // ── Limit names ──
            "5h_limit": "5小时限制",
            "weekly_limit": "每周限制",
            "fable_limit": "Fable 限制",
            "fable_rate_limited": "已达限制",
            "monthly_limit": "每月限制",
            "daily_tokens": "每日令牌",
            "tier_usage": "层级用量",
            "ag_group_gemini": "Gemini 模型",
            "ag_group_other": "Claude & GPT 模型",
            "premium_requests": "高级请求",
            "chat_limit": "聊天",
            "daily_limit": "每日限制",
            // ── Window labels (detailLines) ──
            "window_label": "窗口",
            "window_monthly": "每月",
            "window_quota": "配额",
            "window_tier": "层级",
            "window_win": "窗口",
            "window_24h_tokens": "24小时令牌",
            // ── Misc ──
            "used": "已用",
            "credits": "积分",
            "expire_label": "过期",
            "issued_label": "发放",
            "coupon_reason_label": "原因",
            "coupon_issued_label": "发放",
            "coupon_expire_label": "过期",
            "reset_coupons": "重置优惠券",
            "coupon_usage": "使用奖励",
            "coupon_referral": "推荐",
            "warn_weekly_closing": "%d小时后重置 — 每周限制即将关闭",
            "weekly_short": "每周",
            "finishes_soon": "即将结束",
            // ── Layout experiment (usable-first, spec §2) ──
            "layout": "布局",
            "layout_classic": "经典",
            "layout_usable_first": "可用优先",
            "use_now_header": "立即可用",
            "limited_header": "受限 / 冷却中",
            "blocked_header": "已阻断",
            "other_header": "其他",
            "usable_count": "可用",
            "pct_left": "剩余",
            "resets_in": "%@ 后重置",
            "usable_now": "已重置 · 可用",
            "quota_exhausted": "配额耗尽",
            "token_expired_reconnect": "令牌过期 · 重新连接",
            "error_prefix": "错误",
            "sub_expired_on": "订阅过期 %@",
            // ── Subscription line (account submenus) ──
            "sub_paid": "已付费",
            "sub_free": "免费",
            "sub_renews": "%@ 续订",
            "sub_renews_soon": "即将续订 %@",
            "sub_expired_since": "自 %@ 过期",
            "sub_expired": "已过期",
        ],
        .ja: [
            // ── Footer ──
            "poll_now": "今すぐポーリング",
            "open_dashboard": "ダッシュボードを開く",
            "refresh_display": "表示を更新",
            "add_new_agent": "新しいエージェントを追加",
            "manage_accounts": "アカウントを管理…",
            "language": "言語",
            "quit": "終了",
            "heartbeat": "Heartbeat",
            "heartbeat_next": "次回",
            "heartbeat_last": "前回",
            "heartbeat_last_success": "最終成功",
            "run_heartbeat_now": "今すぐハートビート実行",
            "heartbeat_success": "成功",
            "heartbeat_fail": "失敗",
            "heartbeat_unknown": "不明",
            "reconnect_agent": "このアカウントを再接続",
            "swap_to_agent": "このアカウントに切り替え",
            "devin_api_key_title": "Devin を再接続",
            "devin_api_key_message": "この Devin アカウントの API キーを入力してください。",
            "delete_agent": "このエージェントを削除",
            "delete_agent_confirm": "%@ をエージェントプールから削除しますか？この操作は元に戻せません。",
            "cancel": "キャンセル",
            // ── Group headers ──
            "status": "ステータス",
            "limit_session": "リミットセッション",
            "resets": "リセット",
            "subscription": "サブスクリプション",
            // ── Labels ──
            "plan": "プラン",
            "token_expires": "トークン期限",
            "last_poll": "最終ポーリング",
            "additional_credits": "追加クレジット",
            "banked_resets": "蓄積リセット",
            "binding_window": "バインディングウィンドウ",
            "rate_limit_tier": "レート制限ティア",
            "billing": "課金",
            "extra_usage": "追加使用",
            "subscribed": "登録日",
            "member_since": "メンバー開始",
            "org": "組織",
            "account": "アカウント",
            "monthly_credits": "月間クレジット",
            "on_demand_cap": "オンデマンド上限",
            "billing_period": "課金期間",
            "tier": "ティア",
            "description": "説明",
            "active_session_tier": "アクティブセッションティア",
            "premium_entitlement": "プレミアム権限",
            "premium_overage": "プレミアム超過",
            "chat": "チャット",
            "completions": "補完",
            "upgradeable": "アップグレード可",
            "credit_balance": "クレジット残高",
            "plan_started": "プラン開始",
            "plan_resets": "プランリセット",
            "plan_expires": "プラン期限",
            "remaining": "残り",
            "reset": "リセット",
            "limit": "上限",
            "monthly": "月間",
            "sku": "SKU",
            "quota_limit": "クォータ上限",
            "quota_reset": "クォータリセット",
            "account_created": "アカウント作成",
            "payment_history": "過去の支払い",
            // ── Messages ──
            "no_details": "詳細なし",
            "na": "情報なし",
            "updated": "更新",
            "loading": "読み込み中…",
            // ── Booleans ──
            "on": "オン",
            "off": "オフ",
            "unlimited": "無制限",
            "limited": "制限あり",
            "yes": "はい",
            "no": "いいえ",
            // ── Limit names ──
            "5h_limit": "5時間制限",
            "weekly_limit": "週間制限",
            "fable_limit": "Fable 制限",
            "fable_rate_limited": "制限に達しました",
            "monthly_limit": "月間制限",
            "daily_tokens": "日次トークン",
            "tier_usage": "ティア使用量",
            "ag_group_gemini": "Gemini モデル",
            "ag_group_other": "Claude & GPT モデル",
            "premium_requests": "プレミアムリクエスト",
            "chat_limit": "チャット",
            "daily_limit": "日次制限",
            // ── Window labels (detailLines) ──
            "window_label": "ウィンドウ",
            "window_monthly": "月間",
            "window_quota": "クォータ",
            "window_tier": "ティア",
            "window_win": "ウィンドウ",
            "window_24h_tokens": "24時間トークン",
            // ── Misc ──
            "used": "使用済み",
            "credits": "クレジット",
            "expire_label": "期限",
            "issued_label": "発行",
            "coupon_reason_label": "理由",
            "coupon_issued_label": "発行",
            "coupon_expire_label": "期限",
            "reset_coupons": "リセットクーポン",
            "coupon_usage": "使用報酬",
            "coupon_referral": "紹介",
            "warn_weekly_closing": "%d時間後にリセット — 週間制限終了間近",
            "weekly_short": "週間",
            "finishes_soon": "まもなく終了",
            // ── Layout experiment (usable-first, spec §2) ──
            "layout": "レイアウト",
            "layout_classic": "クラシック",
            "layout_usable_first": "使用可能優先",
            "use_now_header": "今すぐ使用",
            "limited_header": "制限 / クールダウン中",
            "blocked_header": "ブロック",
            "other_header": "その他",
            "usable_count": "使用可能",
            "pct_left": "残り",
            "resets_in": "%@ 後にリセット",
            "usable_now": "リセット済み · 使用可能",
            "quota_exhausted": "クォータ枯渇",
            "token_expired_reconnect": "トークン期限切れ · 再接続",
            "error_prefix": "エラー",
            "sub_expired_on": "サブスク期限切れ %@",
            // ── Subscription line (account submenus) ──
            "sub_paid": "有料",
            "sub_free": "無料",
            "sub_renews": "%@ 更新",
            "sub_renews_soon": "まもなく更新 %@",
            "sub_expired_since": "%@ から期限切れ",
            "sub_expired": "期限切れ",
        ],
    ]

    /// Look up a translated string. Falls back to English, then to the key itself.
    static func tr(_ key: String) -> String {
        table[lang]?[key] ?? table[.en]?[key] ?? key
    }

    /// "Label: value" with a translated label.
    static func label(_ key: String, _ value: String) -> String {
        "\(tr(key)): \(value)"
    }

    /// "limitName: pct% used" with optional "(reset: r)" suffix — all parts translated.
    static func usedLine(_ limitKey: String, _ pct: String, reset: String? = nil) -> String {
        var line = "\(tr(limitKey)): \(pct)% \(tr("used"))"
        if let reset { line += " (\(tr("reset")): \(reset))" }
        return line
    }

    /// Translate a boolean-like value via its key ("on"/"off", "yes"/"no", etc.).
    static func bool(_ key: String) -> String { tr(key) }
}
